```{r knitsetup, echo=FALSE, results='markup', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir = './', fig.path = 'figure/figura-', out.format = 'md', unnamed.chunk.label = "Ejemplo", upload.fun = imgur_upload, base.url = "https://rsanchezs.imgur.com/all/")
opts_chunk$set(prompt = FALSE, comment = '##', results = 'markup', collapse = TRUE, eval = TRUE, echo = TRUE, tidy = TRUE)
```




# Estructuras de Control

También llamadas como, __estructura básica__ o __sentencia de control__ se utilizan
para controlar el flujo de un programa (o bloque de instrucciones), son métodos que 
permiten especificar el orden en el cual se ejecutarán las instrucciones en un 
algoritmo. Si no existieran las __estructuras de control__, los programas se ejecutarían
linealmente desde el principio hasta el fin, sin la posibilidad de tomar decisiones.

Por lo general, en la mayoría de lenguajes de programación  encontraremos dos tipos de estructuras
de control. Encontraremos un tipo que permite la ejecución condicional de bloques de 
código y que son conocidas como __estructuras condicionales__. Por otro lado, 
encontraremos las __estructuras iterativas__ que permiten la repetición de un bloque
de instrucciones, un número determinado de veces o mientras se cumpla una condición.

De acuerdo con el manual base de R, las estructuras condicionales corresponden a 
las palabras reservadas `if` y su variante con `else`. Por otro parte, las estructuras 
para bucles son `for`, `while` y `repeat`, con las cláusulas adicionales `break` y `next`.
Podemos consultar las diferentes estructuras de control mediante el comando `?Control` en RStudio.

## Objetivos 

Después de leer este capítulo, deberíamos:

- Ser capaces de controlar el flujo de ejecución con la ayuda de las estructuras 
condicionales.
- Estar capacitado para ejecutar bloques de código repetidamente mediante estructuras
iterativas.